version: "3.7"

services:
  core:
    container_name: soap_app
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./core:/core
    command: "gunicorn -c gunicorn.py core.wsgi"
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
    restart: on-failure